import/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^import/', include('modificar_formulas.urls')),
	url(r'^admin/', admin.site.urls),
]

modificar_formulas/urls.py
from django.conf.urls import url 
from . import views

app_name= 'modificar_formulas'
urlpatterns = [
	url(r'^$', views.mod_formulas, name ='mod_formulas'), # configuración de la url para la VISTA (view) de inicio o index
	url(r'^operar/$', views.operar, name = 'operar'),	  # url invocada cuando se presiona el botón ENVIAR de la sección FORMULAS
	url(r'^generando_tabla/$', views.cargar_tabla, name = "cargar_tabla"),	#se invoca esta url cuando el usuario selecciona un año
]

modificar_formulas/models.py
from django.db import models

# Create your models here.

modificar_formulas/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
#from modificar_formulas.models import Inventario   #import la informacion de la bd
#from modificar_formulas.formulas import Formulas

def mod_formulas(request): #VISTA(view) de inicio o index

		#lista = bd.objects.all() #Obtengo toda la info almacenada en la bd mediante el método objects.all(), lo guardo en lista.
		#return render(request, 'modificar_formulas/mod_formulas.html', {'lista': lista,}) # Devuelvo el objeto HTML (y la lista que va a ser -  
																						  # manejada dentro del código en la página HTML)

def operar(request):

	"""indices = request.GET.getlist('chk_tab')
	lista = Inventario.objects.all()
	opcion = request.GET['radio_formula']				     #con este metodo obtengo la longitud de la lista (o cantidad de filas seleccionada)

	dimension = len(indices)

	if request.GET['radio_formula'] == 'sum':
		#return HttpResponse(Formulas.sumatoria(indices, opcion))
		return render(request, 'modificar_formulas/mod_formulas.html', {'lista': lista, 'result_op': Formulas.sumatoria(indices, opcion),})

	elif request.GET['radio_formula'] == 'prom':
		return render(request, 'modificar_formulas/mod_formulas.html', {'lista': lista, 'result_op': Formulas.promedio(indices, opcion),})

	else:
		return HttpResponse('Fila(s) seleccionada para ACUMULACIO: '+str(dimension)) #una prueba"""

def cargar_tabla(request):
	"""lista = Inventario.objects.filter(id=request.GET['radio_year'])
	return render(request, 'modificar_formulas/mod_formulas.html', {'lista': lista,})"""

modificar_formulas/templates/modificar_formulas/mod_formulas.html
<!DOCTYPE htmal>
<html lang="es">
    <meta charset="utf-8">
    <head>
    <title>Modificar Fórmulas</title>
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'estilos/styles_1.css' %}" />
        <link rel="stylesheet" href="{% static 'estilos/button.css' %}" />
        <script src="{% static 'scripts/script_1.js' %}"></script>
    </head>
    
    <body>
        <header></header>
        <menu>
            <ul><a href=""><li>Inicio</li></a></ul>
        </menu>
        <section id="contenedor">
            
            <article id="articulo1">  
            <form name="generar_t" action="{% url 'modificar_formulas:cargar_tabla' %}" method="get">
                    <article id="conten_radio"> 
                            <input name="radio_year" type="radio" value="1" checked> 2014
                            <input name="radio_year" type="radio" value="2"> 2015
                            <input type="submit" value="Generar Tabla" class="button"> 
                    </article>
            </form>
            <form name="formulario" action="{% url 'modificar_formulas:operar' %}" method="get">    
                        <article class="marco_tabla">
                            <table>
                                <thead id="t_encabezado">
                                    <tr style="">
                                        <th>CODIGO</th>
                                        <th>DESRIPCION</th>
                                        <th>COSTO UNITARIO</th>
                                        <th>CANTIDADES UNITARIAS</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if lista %}
                                    {% for art in lista %}
                                        <tr id = "{{ forloop.counter }}" class="deseleccionada" onclick="seleccionarFila(this, id)">
                                            
                                            <td><input name="chk_tab" type="checkbox" value="{{ forloop.counter }}" class="chk" id ="chk{{ forloop.counter }}">{{ art.codigo}}</td>
                                            <td>{{ art.descripcion }}</td>
                                            <td>{{ art.valor_unitario }}</td>
                                            <td>{{ art.cantidades }}</td>
                                        </tr>
                                    {% endfor %}
                                {% else %}
                                    <p>No hay datos para mostrar</p>
                                {% endif %}
                                </tbody>
                            </table>
                        </article><!-- aquí termina, <article id="marco_tabla"> -->        
            </article> <!-- termina, <article id="articulo1">  -->
                
            </section>
            
            <aside id="derecho">
                
                <article id="list_der">
                    <ul id="lista_derecha">
                        <li id="sumatoria_titulo">Fórmulas</li>
                    </ul>
                </article>
                
                <article id="formulas_text">
                    <ul id="formulas_ul">
                        <li><input name="radio_formula" type="radio" value="sum" checked> SUMATORIA</li>
                        <br><br>
                        <li><input name="radio_formula" type="radio" value="prom"> PROMEDIO</li>
                        <br><br>
                        <li><input name="radio_formula" type="radio" value="acu"> ACUMULACION</li>
                    </ul>
                </article>
                
                <article id="art_btn_summit">
                    <input type="submit" value="Enviar" class="button" onclick="probar(this)">
                </article>

                <article id="espacio_resultado"><!-- este article contendrá el resultado esperado por el usuario -->
                    {% if result_op %}
                        {{result_op}}
                    {% else %}
                        Aquí se mostrará el resultado
                    {% endif %}
                </article>
                
            </form>
        </aside>
    </body>
</html>